# Generated by Django 3.0.5 on 2021-04-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_auto_20210419_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
