# Generated by Django 3.0.5 on 2021-04-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0005_auto_20210419_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
