# Generated by Django 3.0.5 on 2021-04-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0006_auto_20210419_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirm_password',
        ),
    ]
