# Generated by Django 3.0.5 on 2021-04-21 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0007_remove_customuser_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwt',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
