# Generated by Django 3.0.5 on 2021-04-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0008_auto_20210421_0536'),
        ('user_control', '0008_auto_20210421_0507'),
    ]

    operations = [
    ]
