# Generated by Django 3.0.5 on 2021-05-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0011_auto_20210501_0756'),
        ('user_control', '0010_auto_20210501_0932'),
    ]

    operations = [
    ]
