# Generated by Django 3.1.7 on 2021-03-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210315_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
