# Generated by Django 3.0.5 on 2021-05-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_cashondelivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
