# Generated by Django 3.1.7 on 2021-03-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210311_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Sony', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.CharField(default='Hasan', max_length=50),
        ),
    ]
